site_name: KATIAU

nav:
  - K.A.T.I.A.U âš¡: index.md
  - Como Documentar: como_documentar.md
  - Projeto Conceitual: Documentacao
  - Atas: Atas
  
theme: readthedocs
plugins:
  - search
  - include_dir_to_nav
