site_name: KATIAU

nav:
  - K.A.T.I.A.U âš¡: index.md
  - Como Documentar: como_documentar.md
  - Projeto Conceitual: Documentacao
  - Atas: Atas

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
theme: readthedocs

plugins:
  - search
  - include_dir_to_nav
